import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: 40,
  },
  backButton: {
    padding: 20,
  },
  backArrow: {
    fontSize: 24,
    color: '#000',
  },
  logo: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#2C94CB',
    textAlign: 'center',
    marginTop: 40,
    marginBottom: 40,
  },
  logoSmall: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#2C94CB',
    textAlign: 'center',
    marginBottom: 40,
  },
  content: {
    flex: 1,
    paddingHorizontal: 30,
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
    textAlign: 'center',
    marginBottom: 20,
  },
  subtitle: {
    fontSize: 15,
    color: '#666',
    textAlign: 'center',
    lineHeight: 24,
  },
  robotContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  robot: {
    alignItems: 'center',
  },
  robotHead: {
    width: 100,
    height: 80,
    backgroundColor: '#2C94CB',
    borderRadius: 40,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 20,
    borderWidth: 3,
    borderColor: '#000',
  },
  robotEye: {
    width: 20,
    height: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  robotBook: {
    width: 140,
    height: 100,
    backgroundColor: '#fff',
    borderWidth: 3,
    borderColor: '#000',
    marginTop: -5,
    borderRadius: 5,
  },
  nextButton: {
    marginBottom: 40,
    alignSelf: 'center',
  },
  nextButtonText: {
    fontSize: 16,
    color: '#2C94CB',
    fontWeight: '600',
  },
  formContainer: {
    paddingHorizontal: 30,
    flex: 1,
  },
  formTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2C94CB',
    marginBottom: 10,
  },
  formSubtitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 30,
    lineHeight: 20,
  },
  label: {
    fontSize: 16,
    color: '#2C94CB',
    fontWeight: '600',
    marginBottom: 8,
    marginTop: 15,
  },
  input: {
    borderWidth: 2,
    borderColor: '#2C94CB',
    borderRadius: 8,
    padding: 15,
    fontSize: 14,
    color: '#000',
  },
  forgotPassword: {
    color: '#F9690E',
    fontSize: 14,
    textAlign: 'right',
    marginTop: 10,
    fontWeight: '600',
  },
  primaryButton: {
    backgroundColor: '#2C94CB',
    borderRadius: 25,
    padding: 16,
    alignItems: 'center',
    marginTop: 30,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  signupContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  signupText: {
    color: '#666',
    fontSize: 14,
  },
  signupLink: {
    color: '#2C94CB',
    fontSize: 14,
    fontWeight: 'bold',
  },
  codeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 30,
  },
  codeInput: {
    width: 70,
    height: 70,
    borderWidth: 2,
    borderColor: '#2C94CB',
    borderRadius: 8,
    textAlign: 'center',
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
  },
  resendContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  resendText: {
    color: '#666',
    fontSize: 14,
  },
  resendLink: {
    color: '#2C94CB',
    fontSize: 14,
    fontWeight: 'bold',
  },
  mainRobotContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainRobot: {
    alignItems: 'center',
    position: 'relative',
  },
  mainRobotAntenna: {
    width: 3,
    height: 30,
    backgroundColor: '#5CD6A6',
    position: 'absolute',
    top: -30,
  },
  mainRobotHead: {
    width: 120,
    height: 100,
    backgroundColor: '#5CD6A6',
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainRobotEyes: {
    width: 80,
    height: 40,
    backgroundColor: '#000',
    borderRadius: 20,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 15,
  },
  mainRobotEye: {
    width: 12,
    height: 12,
    backgroundColor: '#fff',
    borderRadius: 6,
  },
  mainRobotBody: {
    width: 100,
    height: 80,
    backgroundColor: '#5CD6A6',
    borderRadius: 15,
    marginTop: 5,
  },
  buttonContainer: {
    paddingHorizontal: 30,
    paddingBottom: 40,
  },
  secondaryButton: {
    backgroundColor: '#fff',
    borderRadius: 25,
    padding: 16,
    alignItems: 'center',
    marginTop: 15,
    borderWidth: 2,
    borderColor: '#2C94CB',
  },
  secondaryButtonText: {
    color: '#2C94CB',
    fontSize: 16,
    fontWeight: 'bold',
  },
  socialText: {
    textAlign: 'center',
    color: '#666',
    fontSize: 13,
    marginTop: 30,
    marginBottom: 15,
  },
  socialButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 15,
  },
  socialButton: {
    width: 45,
    height: 45,
    borderRadius: 23,
    backgroundColor: '#2C94CB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  socialIcon: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
});