import type { Metadata } from "next";
import { Geist, Geist_Mono, Kufam } from "next/font/google";
import "./globals.css";

/**
 * @Hyckael
 * @marlenegohi
 * @Jojo-225
 * J'ai ajouté la police Kufam qui est la police principale de la maque
 * @this
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const kufamSans = Kufam({
  variable: "--font-kufam-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${kufamSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
